// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyLocalizerSystem.h"
#include "Tutorial_Dialogue_1st_DraftLocalizerSystem.generated.h"

/** Articy Localizer System */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftLocalizerSystem : public UArticyLocalizerSystem
{
	GENERATED_BODY()
	
public:
	void Reload() 
	{
		const FString& LangName = FInternationalization::Get().GetCurrentCulture()->GetTwoLetterISOLanguageName();
		if (!bListenerSet) {
			FInternationalization::Get().OnCultureChanged().AddUObject(this, &UTutorial_Dialogue_1st_DraftLocalizerSystem::Reload);
			bListenerSet = true;
		}
FStringTableRegistry::Get().UnregisterStringTable(FName("All_objects"));
LOCTABLE_FROMFILE_GAME("All_objects", "All_objects", "ArticyContent/Generated/All_objects.csv");
		bDataLoaded = true;
	}
};
