// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "Tutorial_Dialogue_1st_DraftExpressoScripts.h"
#include "Tutorial_Dialogue_1st_DraftDatabase.generated.h"

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UTutorial_Dialogue_1st_DraftDatabase() 
	{
		SetExpressoScriptsClass(UTutorial_Dialogue_1st_DraftExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UTutorial_Dialogue_1st_DraftDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UTutorial_Dialogue_1st_DraftDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UTutorial_Dialogue_1st_DraftGlobalVariables* GetGVs() const override
	{
		return static_cast<UTutorial_Dialogue_1st_DraftGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UTutorial_Dialogue_1st_DraftGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UTutorial_Dialogue_1st_DraftGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
