// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyTypeSystem.h"
#include "Tutorial_Dialogue_1st_DraftTypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftTypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
