// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyBaseInclude.h"
#include "Tutorial_Dialogue_1st_DraftInterfaces.h"
#include "Tutorial_Dialogue_1st_DraftArticyTypes.generated.h"


/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef Sex */
class ETutorial_Dialogue_1st_DraftSex : uint8
{
	Male = 0,
	Female = 1,
	Unknown = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef ShapeType */
class ETutorial_Dialogue_1st_DraftShapeType : uint8
{
	Invalid = 0,
	Spot = 1,
	Circle = 2,
	Rectangle = 3,
	Path = 4,
	Polygon = 5,
	Link = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef SelectabilityModes */
class ETutorial_Dialogue_1st_DraftSelectabilityModes : uint8
{
	Unselectable = 0,
	Selectable = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef VisibilityModes */
class ETutorial_Dialogue_1st_DraftVisibilityModes : uint8
{
	Invisible = 0,
	Visible = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef OutlineStyle */
class ETutorial_Dialogue_1st_DraftOutlineStyle : uint8
{
	Solid = 0,
	Dot = 1,
	Dash = 2,
	DashDot = 3,
	DashDotDot = 4,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PathCaps */
class ETutorial_Dialogue_1st_DraftPathCaps : uint8
{
	ColoredDot = 0,
	None = 1,
	LineArrowHead = 2,
	FilledArrowHead = 3,
	Diamond = 4,
	Square = 5,
	Disc = 6,
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef FlowFragment */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftFlowFragment : public UArticyFlowFragment,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Dialogue */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDialogue : public UArticyDialogue,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef DialogueFragment */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDialogueFragment : public UArticyDialogueFragment,
 public IArticyObjectWithMenuText,
 public IArticyObjectWithStageDirections,
 public IArticyObjectWithSpeaker,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="MenuText"))
	FText MenuText = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StageDirections"))
	FText StageDirections = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Speaker"))
	FArticyId Speaker;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="SplitHeight"))
	float SplitHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef ModelTemplate */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftModelTemplate : public UTutorial_Dialogue_1st_DraftDialogueFragment
{
	GENERATED_BODY()
	
public:
	
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Ghunter */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGhunter : public UTutorial_Dialogue_1st_DraftDialogueFragment
{
	GENERATED_BODY()
	
public:
	
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Hub */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftHub : public UArticyHub,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Comment */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftComment : public UArticyComment,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedBy"))
	FText CreatedBy = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedOn"))
	FDateTime CreatedOn;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Jump */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftJump : public UArticyJump,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Entity */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftEntity : public UArticyEntity,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Basic Character Properties Feature */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Age"))
	float Age = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Species"))
	FText Species = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Born in"))
	FText BornIn = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Sex"))
	ETutorial_Dialogue_1st_DraftSex Sex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Profession"))
	FText Occupation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Voice"))
	FText Accent = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Personality"))
	FText Personality = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Appearance"))
	FText Appearance = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef DefaultSupportingCharacterTemplate */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDefaultSupportingCharacterTemplate : public UTutorial_Dialogue_1st_DraftEntity,
 public ITutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** ITutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Extended Character Properties Feature */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDefaultExtendedCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Goals"))
	FText Motivation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Inner Conflict"))
	FText InnerConflict = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Skills"))
	FText Skills = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Weaknesses"))
	FText Fears = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Quirks / Habits"))
	FText Habits = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Further Details"))
	FText FurtherDetails = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef DefaultMainCharacterTemplate */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDefaultMainCharacterTemplate : public UTutorial_Dialogue_1st_DraftEntity,
 public ITutorial_Dialogue_1st_DraftObjectWithDefaultExtendedCharacterFeatureFeature,
 public ITutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** ITutorial_Dialogue_1st_DraftObjectWithDefaultExtendedCharacterFeatureFeature implementation */
	UTutorial_Dialogue_1st_DraftDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const override
	{
		return DefaultExtendedCharacterFeature;
	}
	/** ITutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Extended Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UTutorial_Dialogue_1st_DraftDefaultExtendedCharacterFeatureFeature* DefaultExtendedCharacterFeature;
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Location */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftLocation : public UArticyLocation,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Spot */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftSpot : public UArticySpot,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ETutorial_Dialogue_1st_DraftOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Zone */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftZone : public UArticyZone,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ETutorial_Dialogue_1st_DraftShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ETutorial_Dialogue_1st_DraftOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Path */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftPath : public UArticyPath,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ETutorial_Dialogue_1st_DraftOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StartCap"))
	ETutorial_Dialogue_1st_DraftPathCaps StartCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="EndCap"))
	ETutorial_Dialogue_1st_DraftPathCaps EndCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="LineWidth"))
	float LineWidth = 0.f;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Link */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftLink : public UArticyLink,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithTarget,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Target"))
	FArticyId Target;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Asset */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftAsset : public UArticyAsset,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Filename"))
	FText Filename = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OriginalSource"))
	FText OriginalSource = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Condition */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftCondition : public UArticyCondition,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptCondition* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Instruction */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftInstruction : public UArticyInstruction,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptInstruction* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationText */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftLocationText : public UArticyLocationText,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ETutorial_Dialogue_1st_DraftShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ETutorial_Dialogue_1st_DraftOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedWidth"))
	float ForcedWidth = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedHeight"))
	float ForcedHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationImage */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftLocationImage : public UArticyLocationImage,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	ETutorial_Dialogue_1st_DraftShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	ETutorial_Dialogue_1st_DraftVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	ETutorial_Dialogue_1st_DraftOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	ETutorial_Dialogue_1st_DraftSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ClipRect"))
	FArticyRect ClipRect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageOpacity"))
	float ImageOpacity = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageAsset"))
	FArticyId ImageAsset;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageWidth"))
	int32 CachedImageWidth = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageHeight"))
	int32 CachedImageHeight = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Document */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftDocument : public UArticyDocument,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef TextObject */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftTextObject : public UArticyTextObject,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef UserFolder */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftUserFolder : public UArticyUserFolder,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithShortId,
 public IArticyObjectWithZIndex
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
};
