// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "Tutorial_Dialogue_1st_DraftInterfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Tutorial_Dialogue_1st_Draft Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UTutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class ITutorial_Dialogue_1st_DraftObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UTutorial_Dialogue_1st_DraftDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Tutorial_Dialogue_1st_Draft Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UTutorial_Dialogue_1st_DraftObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class ITutorial_Dialogue_1st_DraftObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UTutorial_Dialogue_1st_DraftDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
