// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyGlobalVariables.h"
#include "Tutorial_Dialogue_1st_DraftGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGookerExpressionsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerLesson = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerAngry = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerHappy = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerTerrified = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerConfused = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UArticyBool* GookerSad = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGookerExpressionsVariables() 
	{
		GookerLesson = CreateDefaultSubobject<UArticyBool>("GookerLesson");
		GookerAngry = CreateDefaultSubobject<UArticyBool>("GookerAngry");
		GookerHappy = CreateDefaultSubobject<UArticyBool>("GookerHappy");
		GookerTerrified = CreateDefaultSubobject<UArticyBool>("GookerTerrified");
		GookerConfused = CreateDefaultSubobject<UArticyBool>("GookerConfused");
		GookerSad = CreateDefaultSubobject<UArticyBool>("GookerSad");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GookerLesson->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerLesson"), false);
		this->Variables.Add(GookerLesson);
		GookerAngry->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerAngry"), false);
		this->Variables.Add(GookerAngry);
		GookerHappy->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerHappy"), false);
		this->Variables.Add(GookerHappy);
		GookerTerrified->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerTerrified"), false);
		this->Variables.Add(GookerTerrified);
		GookerConfused->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerConfused"), false);
		this->Variables.Add(GookerConfused);
		GookerSad->Init<UArticyBool>(this, Store, TEXT("GookerExpressions.GookerSad"), false);
		this->Variables.Add(GookerSad);
	}
};

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGavernExpressionsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernHappy = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernSad = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernKawaii = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernMysterious = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernAngry = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernAnnoyed = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UArticyBool* GavernSurprised = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGavernExpressionsVariables() 
	{
		GavernHappy = CreateDefaultSubobject<UArticyBool>("GavernHappy");
		GavernSad = CreateDefaultSubobject<UArticyBool>("GavernSad");
		GavernKawaii = CreateDefaultSubobject<UArticyBool>("GavernKawaii");
		GavernMysterious = CreateDefaultSubobject<UArticyBool>("GavernMysterious");
		GavernAngry = CreateDefaultSubobject<UArticyBool>("GavernAngry");
		GavernAnnoyed = CreateDefaultSubobject<UArticyBool>("GavernAnnoyed");
		GavernSurprised = CreateDefaultSubobject<UArticyBool>("GavernSurprised");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GavernHappy->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernHappy"), false);
		this->Variables.Add(GavernHappy);
		GavernSad->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernSad"), false);
		this->Variables.Add(GavernSad);
		GavernKawaii->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernKawaii"), false);
		this->Variables.Add(GavernKawaii);
		GavernMysterious->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernMysterious"), false);
		this->Variables.Add(GavernMysterious);
		GavernAngry->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernAngry"), false);
		this->Variables.Add(GavernAngry);
		GavernAnnoyed->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernAnnoyed"), false);
		this->Variables.Add(GavernAnnoyed);
		GavernSurprised->Init<UArticyBool>(this, Store, TEXT("GavernExpressions.GavernSurprised"), false);
		this->Variables.Add(GavernSurprised);
	}
};

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGoctorExpressionsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorHappy = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorSad = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorConfused = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorDissapointed = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorBroken = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UArticyBool* GoctorTerrified = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGoctorExpressionsVariables() 
	{
		GoctorHappy = CreateDefaultSubobject<UArticyBool>("GoctorHappy");
		GoctorSad = CreateDefaultSubobject<UArticyBool>("GoctorSad");
		GoctorConfused = CreateDefaultSubobject<UArticyBool>("GoctorConfused");
		GoctorDissapointed = CreateDefaultSubobject<UArticyBool>("GoctorDissapointed");
		GoctorBroken = CreateDefaultSubobject<UArticyBool>("GoctorBroken");
		GoctorTerrified = CreateDefaultSubobject<UArticyBool>("GoctorTerrified");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GoctorHappy->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorHappy"), false);
		this->Variables.Add(GoctorHappy);
		GoctorSad->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorSad"), false);
		this->Variables.Add(GoctorSad);
		GoctorConfused->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorConfused"), false);
		this->Variables.Add(GoctorConfused);
		GoctorDissapointed->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorDissapointed"), false);
		this->Variables.Add(GoctorDissapointed);
		GoctorBroken->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorBroken"), false);
		this->Variables.Add(GoctorBroken);
		GoctorTerrified->Init<UArticyBool>(this, Store, TEXT("GoctorExpressions.GoctorTerrified"), false);
		this->Variables.Add(GoctorTerrified);
	}
};

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGailorExpressionsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorHappy = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorSad = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorInsulted = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorDisgusted = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorBored = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorAngry = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorTaunt = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorConfused = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorAmused = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UArticyBool* GailorDread = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGailorExpressionsVariables() 
	{
		GailorHappy = CreateDefaultSubobject<UArticyBool>("GailorHappy");
		GailorSad = CreateDefaultSubobject<UArticyBool>("GailorSad");
		GailorInsulted = CreateDefaultSubobject<UArticyBool>("GailorInsulted");
		GailorDisgusted = CreateDefaultSubobject<UArticyBool>("GailorDisgusted");
		GailorBored = CreateDefaultSubobject<UArticyBool>("GailorBored");
		GailorAngry = CreateDefaultSubobject<UArticyBool>("GailorAngry");
		GailorTaunt = CreateDefaultSubobject<UArticyBool>("GailorTaunt");
		GailorConfused = CreateDefaultSubobject<UArticyBool>("GailorConfused");
		GailorAmused = CreateDefaultSubobject<UArticyBool>("GailorAmused");
		GailorDread = CreateDefaultSubobject<UArticyBool>("GailorDread");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GailorHappy->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorHappy"), false);
		this->Variables.Add(GailorHappy);
		GailorSad->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorSad"), false);
		this->Variables.Add(GailorSad);
		GailorInsulted->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorInsulted"), false);
		this->Variables.Add(GailorInsulted);
		GailorDisgusted->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorDisgusted"), false);
		this->Variables.Add(GailorDisgusted);
		GailorBored->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorBored"), false);
		this->Variables.Add(GailorBored);
		GailorAngry->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorAngry"), false);
		this->Variables.Add(GailorAngry);
		GailorTaunt->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorTaunt"), false);
		this->Variables.Add(GailorTaunt);
		GailorConfused->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorConfused"), false);
		this->Variables.Add(GailorConfused);
		GailorAmused->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorAmused"), false);
		this->Variables.Add(GailorAmused);
		GailorDread->Init<UArticyBool>(this, Store, TEXT("GailorExpressions.GailorDread"), false);
		this->Variables.Add(GailorDread);
	}
};

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGmithExpressionsVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithHappy = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithSad = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithAngry = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithScared = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithAnnoyed = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithDisgusted = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithCrying = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithExcited = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithPanic = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UArticyBool* GmithShock = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGmithExpressionsVariables() 
	{
		GmithHappy = CreateDefaultSubobject<UArticyBool>("GmithHappy");
		GmithSad = CreateDefaultSubobject<UArticyBool>("GmithSad");
		GmithAngry = CreateDefaultSubobject<UArticyBool>("GmithAngry");
		GmithScared = CreateDefaultSubobject<UArticyBool>("GmithScared");
		GmithAnnoyed = CreateDefaultSubobject<UArticyBool>("GmithAnnoyed");
		GmithDisgusted = CreateDefaultSubobject<UArticyBool>("GmithDisgusted");
		GmithCrying = CreateDefaultSubobject<UArticyBool>("GmithCrying");
		GmithExcited = CreateDefaultSubobject<UArticyBool>("GmithExcited");
		GmithPanic = CreateDefaultSubobject<UArticyBool>("GmithPanic");
		GmithShock = CreateDefaultSubobject<UArticyBool>("GmithShock");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GmithHappy->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithHappy"), false);
		this->Variables.Add(GmithHappy);
		GmithSad->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithSad"), false);
		this->Variables.Add(GmithSad);
		GmithAngry->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithAngry"), false);
		this->Variables.Add(GmithAngry);
		GmithScared->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithScared"), false);
		this->Variables.Add(GmithScared);
		GmithAnnoyed->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithAnnoyed"), false);
		this->Variables.Add(GmithAnnoyed);
		GmithDisgusted->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithDisgusted"), false);
		this->Variables.Add(GmithDisgusted);
		GmithCrying->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithCrying"), false);
		this->Variables.Add(GmithCrying);
		GmithExcited->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithExcited"), false);
		this->Variables.Add(GmithExcited);
		GmithPanic->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithPanic"), false);
		this->Variables.Add(GmithPanic);
		GmithShock->Init<UArticyBool>(this, Store, TEXT("GmithExpressions.GmithShock"), false);
		this->Variables.Add(GmithShock);
	}
};

UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftNoteBranchesVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="NoteBranches")
	UArticyBool* GuncleDead = nullptr;
	
	 UTutorial_Dialogue_1st_DraftNoteBranchesVariables() 
	{
		GuncleDead = CreateDefaultSubobject<UArticyBool>("GuncleDead");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		GuncleDead->Init<UArticyBool>(this, Store, TEXT("NoteBranches.GuncleDead"), false);
		this->Variables.Add(GuncleDead);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GookerExpressions")
	UTutorial_Dialogue_1st_DraftGookerExpressionsVariables* GookerExpressions = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GavernExpressions")
	UTutorial_Dialogue_1st_DraftGavernExpressionsVariables* GavernExpressions = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GoctorExpressions")
	UTutorial_Dialogue_1st_DraftGoctorExpressionsVariables* GoctorExpressions = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GailorExpressions")
	UTutorial_Dialogue_1st_DraftGailorExpressionsVariables* GailorExpressions = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="GmithExpressions")
	UTutorial_Dialogue_1st_DraftGmithExpressionsVariables* GmithExpressions = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="NoteBranches")
	UTutorial_Dialogue_1st_DraftNoteBranchesVariables* NoteBranches = nullptr;
	
	 UTutorial_Dialogue_1st_DraftGlobalVariables() 
	{
		/** create the namespaces */
		GookerExpressions = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftGookerExpressionsVariables>("GookerExpressions");
		GavernExpressions = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftGavernExpressionsVariables>("GavernExpressions");
		GoctorExpressions = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftGoctorExpressionsVariables>("GoctorExpressions");
		GailorExpressions = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftGailorExpressionsVariables>("GailorExpressions");
		GmithExpressions = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftGmithExpressionsVariables>("GmithExpressions");
		NoteBranches = CreateDefaultSubobject<UTutorial_Dialogue_1st_DraftNoteBranchesVariables>("NoteBranches");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		GookerExpressions->Init(this);
		this->VariableSets.Add(GookerExpressions);
		GavernExpressions->Init(this);
		this->VariableSets.Add(GavernExpressions);
		GoctorExpressions->Init(this);
		this->VariableSets.Add(GoctorExpressions);
		GailorExpressions->Init(this);
		this->VariableSets.Add(GailorExpressions);
		GmithExpressions->Init(this);
		this->VariableSets.Add(GmithExpressions);
		NoteBranches->Init(this);
		this->VariableSets.Add(NoteBranches);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UTutorial_Dialogue_1st_DraftGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UTutorial_Dialogue_1st_DraftGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
