// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyExpressoScripts.h"
#include "Tutorial_Dialogue_1st_DraftGlobalVariables.h"
#include "Tutorial_Dialogue_1st_DraftExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UTutorial_Dialogue_1st_DraftMethodsProvider : public UInterface { GENERATED_BODY() };
class ITutorial_Dialogue_1st_DraftMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class TINYTAVERNGAME_API UTutorial_Dialogue_1st_DraftExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGookerExpressionsVariables> GookerExpressions = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGavernExpressionsVariables> GavernExpressions = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGoctorExpressionsVariables> GoctorExpressions = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGailorExpressionsVariables> GailorExpressions = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGmithExpressionsVariables> GmithExpressions = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftNoteBranchesVariables> NoteBranches = nullptr;
	mutable TWeakObjectPtr<UTutorial_Dialogue_1st_DraftGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UTutorial_Dialogue_1st_DraftGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		GookerExpressions = gv ? gv->GookerExpressions : nullptr;
		GavernExpressions = gv ? gv->GavernExpressions : nullptr;
		GoctorExpressions = gv ? gv->GoctorExpressions : nullptr;
		GailorExpressions = gv ? gv->GailorExpressions : nullptr;
		GmithExpressions = gv ? gv->GmithExpressions : nullptr;
		NoteBranches = gv ? gv->NoteBranches : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UTutorial_Dialogue_1st_DraftMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UTutorial_Dialogue_1st_DraftExpressoScripts() 
	{
		Instructions.Add(-1421567271, [&]
		{
			(*GookerExpressions->GookerLesson) = true;
		});
		Instructions.Add(1168727127, [&]
		{
			(*GookerExpressions->GookerLesson) = false;
		});
		Instructions.Add(-1458719282, [&]
		{
			(*GookerExpressions->GookerHappy) = false;
		});
		Instructions.Add(2000792520, [&]
		{
			(*GookerExpressions->GookerConfused) = false;
		});
		Instructions.Add(1747805054, [&]
		{
			(*GookerExpressions->GookerLesson) = false;
 (*GookerExpressions->GookerSad) = true;
		});
		Instructions.Add(-1269212728, [&]
		{
			(*GookerExpressions->GookerSad) = false;
		});
		Instructions.Add(1515882599, [&]
		{
			(*GookerExpressions->GookerHappy) = false;
 (*GookerExpressions->GookerLesson) = true;
		});
		Instructions.Add(-1075286744, [&]
		{
			(*GookerExpressions->GookerConfused) = false;
 (*GookerExpressions->GookerLesson) = true;
		});
		Instructions.Add(-474223382, [&]
		{
			(*GookerExpressions->GookerHappy) = true;
		});
		Instructions.Add(1736121460, [&]
		{
			(*GookerExpressions->GookerLesson) = false;
 (*GookerExpressions->GookerHappy) = true;
		});
		Instructions.Add(-1589332876, [&]
		{
			(*GookerExpressions->GookerConfused) = false;
 (*GookerExpressions->GookerAngry) = true;
		});
		Instructions.Add(-1737824879, [&]
		{
			(*GookerExpressions->GookerAngry) = false;
 (*GookerExpressions->GookerHappy) = true;
		});
		Instructions.Add(384547820, [&]
		{
			(*GookerExpressions->GookerConfused) = false;
 (*GookerExpressions->GookerHappy) = true;
		});
		Instructions.Add(-1250895989, [&]
		{
			(*GavernExpressions->GavernAnnoyed) = false;
		});
		Instructions.Add(590408284, [&]
		{
			(*GavernExpressions->GavernSurprised) = false;
		});
		Instructions.Add(1898161768, [&]
		{
			(*GavernExpressions->GavernMysterious) = false;
		});
		Instructions.Add(1712948919, [&]
		{
			(*GavernExpressions->GavernAngry) = false;
		});
		Instructions.Add(-163971857, [&]
		{
			(*GavernExpressions->GavernSurprised) = false;
 (*GavernExpressions->GavernSad) = true;
		});
		Instructions.Add(-866964888, [&]
		{
			(*GavernExpressions->GavernSad) = false;
		});
		Instructions.Add(1634585037, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
		});
		Instructions.Add(-447739426, [&]
		{
			(*GailorExpressions->GailorTaunt) = false;
		});
		Instructions.Add(1836973019, [&]
		{
			(*GailorExpressions->GailorHappy) = false;
		});
		Instructions.Add(1603389867, [&]
		{
			(*GailorExpressions->GailorBored) = false;
		});
		Instructions.Add(-73448326, [&]
		{
			(*GavernExpressions->GavernAnnoyed) = false;
 (*GavernExpressions->GavernMysterious) = true;
		});
		Instructions.Add(-1274345280, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
 (*GavernExpressions->GavernMysterious) = true;
		});
		Instructions.Add(842211458, [&]
		{
			(*GavernExpressions->GavernHappy) = true;
		});
		Instructions.Add(-885799288, [&]
		{
			(*GavernExpressions->GavernAnnoyed) = true;
		});
		Instructions.Add(1863412929, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
		});
		Instructions.Add(1527994127, [&]
		{
			(*GavernExpressions->GavernKawaii) = false;
		});
		Instructions.Add(-1143615666, [&]
		{
			(*GavernExpressions->GavernKawaii) = false;
 (*GavernExpressions->GavernMysterious) = true;
		});
		Instructions.Add(-390000490, [&]
		{
			(*GavernExpressions->GavernMysterious) = true;
		});
		Instructions.Add(2060417516, [&]
		{
			(*GoctorExpressions->GoctorSad) = false;
		});
		Instructions.Add(-402176356, [&]
		{
			(*GoctorExpressions->GoctorConfused) = false;
		});
		Instructions.Add(336479597, [&]
		{
			(*GoctorExpressions->GoctorHappy) = false;
		});
		Instructions.Add(-557069612, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = false;
		});
		Instructions.Add(-1842883309, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = false;
		});
		Instructions.Add(1324067152, [&]
		{
			(*GoctorExpressions->GoctorDissapointed)= false;
		});
		Instructions.Add(-2022353718, [&]
		{
			(*GoctorExpressions->GoctorBroken) = false;
		});
		Instructions.Add(508086326, [&]
		{
			(*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(-1268522060, [&]
		{
			(*GoctorExpressions->GoctorSad) = false;
		});
		Instructions.Add(-1694033843, [&]
		{
			(*GailorExpressions->GailorAmused) = false;
		});
		Instructions.Add(-978179316, [&]
		{
			(*GailorExpressions->GailorAmused) = false;
 (*GailorExpressions->GailorDisgusted) = true;
		});
		Instructions.Add(1145242962, [&]
		{
			(*GailorExpressions->GailorSad) = false;
		});
		Instructions.Add(2068934947, [&]
		{
			(*GailorExpressions->GailorDisgusted) = false;
		});
		Instructions.Add(-1399116734, [&]
		{
			(*GailorExpressions->GailorAmused) = false;
 (*GailorExpressions->GailorTaunt) = true;
		});
		Instructions.Add(-516125543, [&]
		{
			(*GailorExpressions->GailorTaunt) = false;
		});
		Instructions.Add(1921018639, [&]
		{
			(*GailorExpressions->GailorAmused) = true;
		});
		Instructions.Add(-1468041485, [&]
		{
			(*GailorExpressions->GailorConfused) = false;
		});
		Instructions.Add(-1830125395, [&]
		{
			(*GailorExpressions->GailorSad) = false;
		});
		Instructions.Add(-108524411, [&]
		{
			(*GailorExpressions->GailorDread) = false;
		});
		Instructions.Add(-1130092879, [&]
		{
			(*GailorExpressions->GailorHappy) = true;
		});
		Instructions.Add(290379443, [&]
		{
			(*GailorExpressions->GailorAngry) = false;
		});
		Instructions.Add(422120067, [&]
		{
			(*GailorExpressions->GailorDisgusted) = false;
		});
		Instructions.Add(-2096805274, [&]
		{
			(*GailorExpressions->GailorAmused) = false;
		});
		Instructions.Add(2115962394, [&]
		{
			(*GailorExpressions->GailorInsulted) = false;
		});
		Instructions.Add(-1227826270, [&]
		{
			(*GailorExpressions->GailorTaunt) = false;
 (*GailorExpressions->GailorAngry) = true;
		});
		Instructions.Add(-419493298, [&]
		{
			(*GailorExpressions->GailorHappy) = false;
		});
		Instructions.Add(-406124859, [&]
		{
			(*GailorExpressions->GailorBored) = false;
 (*GailorExpressions->GailorHappy) = true;
		});
		Instructions.Add(-50162291, [&]
		{
			(*GailorExpressions->GailorHappy) = false;
 (*GailorExpressions->GailorTaunt) = true;
		});
		Instructions.Add(-532566979, [&]
		{
			(*GailorExpressions->GailorBored) = false;
		});
		Instructions.Add(267680600, [&]
		{
			(*GmithExpressions->GmithHappy) = true;
		});
		Instructions.Add(-153656371, [&]
		{
			(*GmithExpressions->GmithExcited) = true;
		});
		Instructions.Add(715445253, [&]
		{
			(*GmithExpressions->GmithExcited) = false;
		});
		Instructions.Add(1465135326, [&]
		{
			(*GmithExpressions->GmithDisgusted) = false;
		});
		Instructions.Add(-554543652, [&]
		{
			(*GmithExpressions->GmithHappy) = false;
		});
		Instructions.Add(1253375308, [&]
		{
			(*GmithExpressions->GmithDisgusted) = false;
 (*GmithExpressions->GmithHappy) = true;
		});
		Instructions.Add(1758272846, [&]
		{
			(*GmithExpressions->GmithShock) = false;
 (*GmithExpressions->GmithAngry) = true;
		});
		Instructions.Add(608007233, [&]
		{
			(*GmithExpressions->GmithAnnoyed) = false;
		});
		Instructions.Add(-1564378956, [&]
		{
			(*GmithExpressions->GmithAngry) = false;
		});
		Instructions.Add(-154703779, [&]
		{
			(*GmithExpressions->GmithHappy) = false;
 (*GmithExpressions->GmithExcited) = true;
		});
		Instructions.Add(1875517016, [&]
		{
			(*GmithExpressions->GmithAngry) = false;
 (*GmithExpressions->GmithShock) = true;
		});
		Instructions.Add(289403828, [&]
		{
			(*GmithExpressions->GmithShock) = false;
 (*GmithExpressions->GmithSad) = true;
		});
		Instructions.Add(-584656880, [&]
		{
			(*GmithExpressions->GmithSad) = false;
 (*GmithExpressions->GmithPanic) = true;
		});
		Instructions.Add(777353081, [&]
		{
			(*GmithExpressions->GmithPanic) = false;
		});
		Instructions.Add(1299882021, [&]
		{
			(*GmithExpressions->GmithCrying) = false;
		});
		Instructions.Add(900375728, [&]
		{
			(*GmithExpressions->GmithShock) = false;
		});
		Instructions.Add(-1752607141, [&]
		{
			(*GailorExpressions->GailorSad) = true;
		});
		Instructions.Add(-43294726, [&]
		{
			(*GailorExpressions->GailorDread) = true;
		});
		Instructions.Add(-1586118592, [&]
		{
			(*GailorExpressions->GailorConfused) = false;
		});
		Instructions.Add(1610752360, [&]
		{
			(*GmithExpressions->GmithSad) = false;
 (*GmithExpressions->GmithHappy) = true;
		});
		Instructions.Add(492758181, [&]
		{
			(*GavernExpressions->GavernAngry) = false;
		});
		Instructions.Add(-1708309080, [&]
		{
			(*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(2005271028, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = true;
		});
		Instructions.Add(1537388564, [&]
		{
			(*GoctorExpressions->GoctorHappy) = false;
 (*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(468300778, [&]
		{
			(*GmithExpressions->GmithSad) = false;
 (*GmithExpressions->GmithCrying) = true;
		});
		Instructions.Add(-1193977173, [&]
		{
			(*GmithExpressions->GmithCrying) = false;
		});
		Instructions.Add(-202073195, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
		});
		Instructions.Add(1733944658, [&]
		{
			(*GavernExpressions->GavernSad) = true;
		});
		Instructions.Add(1878857933, [&]
		{
			(*GavernExpressions->GavernKawaii) = false;
 (*GavernExpressions->GavernHappy) = true;
		});
		Instructions.Add(377641270, [&]
		{
			(*GavernExpressions->GavernKawaii) = true;
		});
		Instructions.Add(-1893799221, [&]
		{
			(*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(662475439, [&]
		{
			(*GoctorExpressions->GoctorBroken) = false;
 (*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(803730736, [&]
		{
			(*GmithExpressions->GmithSad) = true;
		});
		Instructions.Add(731288413, [&]
		{
			(*GmithExpressions->GmithSad) = false;
		});
		Instructions.Add(-143436501, [&]
		{
			(*GmithExpressions->GmithShock) = false;
 (*GmithExpressions->GmithCrying) = true;
		});
		Instructions.Add(1015374846, [&]
		{
			(*GmithExpressions->GmithHappy) = false;
		});
		Instructions.Add(-871576255, [&]
		{
			(*GailorExpressions->GailorAngry) = false;
 (*GailorExpressions->GailorSad) = true;
		});
		Instructions.Add(341742904, [&]
		{
			(*GailorExpressions->GailorSad) = false;
		});
		Instructions.Add(-1462653510, [&]
		{
			(*GoctorExpressions->GoctorBroken) = true;
		});
		Instructions.Add(-1858739274, [&]
		{
			(*GoctorExpressions->GoctorTerrified) = false;
 (*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(-1886912464, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = false;
 (*GoctorExpressions->GoctorTerrified) = true;
		});
		Instructions.Add(1813498582, [&]
		{
			(*GoctorExpressions->GoctorTerrified) = false;
		});
		Instructions.Add(620386644, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = true;
 (*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(-845143293, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = true;
 (*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(-1982138143, [&]
		{
			(*GoctorExpressions->GoctorHappy) = false;
		});
		Instructions.Add(1899294870, [&]
		{
			(*GoctorExpressions->GoctorTerrified) = false;
 (*GoctorExpressions->GoctorConfused) = true;
		});
		Instructions.Add(94664357, [&]
		{
			(*GoctorExpressions->GoctorConfused) = false;
		});
		Instructions.Add(853014049, [&]
		{
			(*GoctorExpressions->GoctorSad) = false;
		});
		Instructions.Add(-160607107, [&]
		{
			(*GailorExpressions->GailorHappy) = true;
		});
		Instructions.Add(-87276659, [&]
		{
			(*GookerExpressions->GookerAngry) = false;
 (*GookerExpressions->GookerLesson) = true;
		});
		Instructions.Add(-717317978, [&]
		{
			(*GookerExpressions->GookerAngry) = false;
		});
		Instructions.Add(-1319870144, [&]
		{
			(*GookerExpressions->GookerTerrified) = false;
 (*GookerExpressions->GookerHappy) = true;
		});
		Instructions.Add(-1916401267, [&]
		{
			(*GavernExpressions->GavernSad) = false;
 (*GavernExpressions->GavernMysterious) = true;
		});
		Instructions.Add(1425409318, [&]
		{
			(*GavernExpressions->GavernSurprised) = false;
 (*GavernExpressions->GavernAngry) = true;
		});
		Instructions.Add(-235317737, [&]
		{
			(*GookerExpressions->GookerConfused) = false;
 (*GookerExpressions->GookerTerrified) = true;
		});
		Instructions.Add(-1563892113, [&]
		{
			(*GookerExpressions->GookerTerrified) = false;
		});
		Instructions.Add(1262735256, [&]
		{
			(*GookerExpressions->GookerConfused) = true;
		});
		Instructions.Add(-1134552700, [&]
		{
			(*GavernExpressions->GavernSurprised) = true;
		});
		Instructions.Add(-2041689341, [&]
		{
			(*GavernExpressions->GavernAngry) = true;
		});
		Instructions.Add(-1795126022, [&]
		{
			(*GailorExpressions->GailorTaunt) = true;
		});
		Instructions.Add(1481753841, [&]
		{
			(*GailorExpressions->GailorBored) = true;
		});
		Instructions.Add(-92445077, [&]
		{
			(*GavernExpressions->GavernHappy) = true;
		});
		Instructions.Add(740737639, [&]
		{
			(*GoctorExpressions->GoctorConfused) = true;
		});
		Instructions.Add(154630837, [&]
		{
			(*GoctorExpressions->GoctorDissapointed) = true;
		});
		Instructions.Add(1919976086, [&]
		{
			(*GoctorExpressions->GoctorHappy) = false;
 (*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(-505424310, [&]
		{
			(*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(757713323, [&]
		{
			(*GailorExpressions->GailorDisgusted) = true;
		});
		Instructions.Add(979726310, [&]
		{
			(*GailorExpressions->GailorConfused) = true;
		});
		Instructions.Add(-548164876, [&]
		{
			(*GailorExpressions->GailorSad) = true;
		});
		Instructions.Add(-497986690, [&]
		{
			(*GailorExpressions->GailorAngry) = true;
		});
		Instructions.Add(-532554107, [&]
		{
			(*GailorExpressions->GailorDisgusted) = true;
		});
		Instructions.Add(-415096602, [&]
		{
			(*GailorExpressions->GailorInsulted) = true;
		});
		Instructions.Add(1554411, [&]
		{
			(*GailorExpressions->GailorAmused) = true;
		});
		Instructions.Add(-998152691, [&]
		{
			(*GailorExpressions->GailorBored) = true;
		});
		Instructions.Add(-793801121, [&]
		{
			(*GmithExpressions->GmithDisgusted) = true;
		});
		Instructions.Add(-1733834313, [&]
		{
			(*GmithExpressions->GmithAnnoyed) = true;
		});
		Instructions.Add(-1363539178, [&]
		{
			(*GmithExpressions->GmithShock) = true;
		});
		Instructions.Add(1359023767, [&]
		{
			(*GmithExpressions->GmithAngry) = true;
		});
		Instructions.Add(259105420, [&]
		{
			(*GmithExpressions->GmithPanic) = true;
		});
		Instructions.Add(1765648446, [&]
		{
			(*GmithExpressions->GmithCrying) = true;
		});
		Instructions.Add(-898444296, [&]
		{
			(*GmithExpressions->GmithShock) = true;
		});
		Instructions.Add(1236493288, [&]
		{
			(*GmithExpressions->GmithAngry)= true;
		});
		Instructions.Add(-1983193112, [&]
		{
			(*GailorExpressions->GailorConfused)= true;
		});
		Instructions.Add(1824937293, [&]
		{
			(*GavernExpressions->GavernAngry) = true;
		});
		Instructions.Add(1058590755, [&]
		{
			(*GmithExpressions->GmithHappy) = false;
 (*GmithExpressions->GmithSad) = true;
		});
		Instructions.Add(530387466, [&]
		{
			(*GmithExpressions->GmithHappy) = false;
 (*GmithExpressions->GmithExcited) = true;
		});
		Instructions.Add(-1073481559, [&]
		{
			(*GavernExpressions->GavernKawaii) = true;
		});
		Instructions.Add(1463438087, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
 (*GavernExpressions->GavernKawaii) = true;
		});
		Instructions.Add(716411967, [&]
		{
			(*GavernExpressions->GavernHappy) = false;
 (*GavernExpressions->GavernMysterious) = true;
		});
		Conditions.Add(-162031793, [&]
		{
			return ConditionOrTrue(
				(*NoteBranches->GuncleDead) == true
			);
		});
		Instructions.Add(1930946874, [&]
		{
			(*GoctorExpressions->GoctorConfused) = true;
		});
		Instructions.Add(1622770260, [&]
		{
			(*GmithExpressions->GmithShock) = true;
		});
		Instructions.Add(110600120, [&]
		{
			(*GoctorExpressions->GoctorSad) = false;
 (*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(-760771135, [&]
		{
			(*GoctorExpressions->GoctorTerrified) = true;
		});
		Instructions.Add(-173802321, [&]
		{
			(*GoctorExpressions->GoctorConfused) = true;
		});
		Instructions.Add(162201438, [&]
		{
			(*GoctorExpressions->GoctorHappy) = true;
		});
		Instructions.Add(1735115743, [&]
		{
			(*GoctorExpressions->GoctorSad) = true;
		});
		Instructions.Add(-1118922459, [&]
		{
			(*GookerExpressions->GookerAngry) = true;
		});
		Instructions.Add(1306615957, [&]
		{
			(*GookerExpressions->GookerTerrified) = true;
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
